---
hide_from_search_engines: true

title: Grand Park

permalink: pretty
future: true # https://jekyllrb.com/docs/upgrading/2-to-3/#future-posts

hide_from_search_engines: true
use_analytics: false

use_theme_sunday: true
use_illustrations: true
use_sunshine: false
use_dark_on_light: false
use_unit: true

events_today: false
events_tomorrow: false

# announcement: The splash pad is closed today (Saturday, September 22, 2018) for a private event.

collections:
  announcements:
    title: Announcements
    output: false
  events:
    title: Events
    output: true
    permalink: /events/:year/:month/:day/:title/
#   posts:
#     title: Blog
#     output: true

defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    layout: default
# - scope:
#     path: ''
#     type: posts
#   values:
#     excerpt: ''
#     author: ''
#     categories: blog
#     layout: post

exclude:
- CNAME
- README
- Gemfile
- Gemfile.lock
- _node

version: 0.0.149

